import type { Hex } from "viem";

/**
 * Frozen known-answer vectors for ERC-5564 scheme 1.
 *
 * ERC-5564 ships no hex test vectors of its own, so these were produced by running ScopeLift's
 * `stealth-address-sdk` — the implementation the ecosystem built against — over fixed inputs, and
 * every value here was generated by that SDK rather than by the code under test. The inputs are a
 * keccak chain from a published label, so they are reproducible and obviously not cherry-picked.
 *
 * `reference.test.ts` checks us against that SDK live. This file does the same job without it: if
 * the dev dependency is ever dropped or drifts, these still pin the exact bytes. Never regenerate
 * them from our own output — that would turn a compatibility test into a snapshot of whatever we
 * happen to do today.
 */

export type StealthVector = {
  spendingPrivateKey: Hex;
  viewingPrivateKey: Hex;
  spendingPublicKey: Hex;
  viewingPublicKey: Hex;
  metaAddress: Hex;
  ephemeralPrivateKey: Hex;
  ephemeralPublicKey: Hex;
  viewTag: Hex;
  stealthAddress: Hex;
  stealthPrivateKey: Hex;
};

export const STEALTH_VECTORS: StealthVector[] = [
  {
    spendingPrivateKey: "0x63d884d195cc4fc050517948691d79d33327f7ec7337951a7cf6288233a472f6",
    viewingPrivateKey: "0xe1831afe692f8271b37bfb04fd06930a607a94016949249c8c0dc9a77ab73eae",
    spendingPublicKey: "0x03f64939bfff616d5e8dbea8c2dc94db1bf6e8e269f4e7051d33552097b0a4570d",
    viewingPublicKey: "0x02d7cc2048044117626327fb91f08cf8e98a7bf11baf73cba2580b8bc3fcd479e3",
    metaAddress: "0x03f64939bfff616d5e8dbea8c2dc94db1bf6e8e269f4e7051d33552097b0a4570d02d7cc2048044117626327fb91f08cf8e98a7bf11baf73cba2580b8bc3fcd479e3",
    ephemeralPrivateKey: "0x73fab09b37f5f5837e1a54e5110818427f44fadc52c3a8fdf4778d4701a210c4",
    ephemeralPublicKey: "0x0367859cd7885e3bd54c0f6bd7dea9c33b853a9615210d0d2fb2fc62b17686fa0e",
    viewTag: "0xf5",
    stealthAddress: "0x0e2b281E4b19eF7Fcd4f1BE0D2f27dADb328F65d",
    stealthPrivateKey: "0x5902f73c92c59f8b67338e1e14fa5e12fd4f93966d55f762e20190f3f2a2b076",
  },
  {
    spendingPrivateKey: "0x8b7438c7e820026ba2f87dfc9c2c90d8959a406aced247f3c29966bca56ffe73",
    viewingPrivateKey: "0x4676242a12fafcd45a6ab1b0ec82885ff2bebd5802cef22e0b1949705d79c8dc",
    spendingPublicKey: "0x03d8e1d9f6f62464926792685ee17c913abf5a7c88bb8f651408306f53027b1b4f",
    viewingPublicKey: "0x02c7a6bc58a25e6fb7722467b506151952ab55d3879eb046ec385381b731c7809e",
    metaAddress: "0x03d8e1d9f6f62464926792685ee17c913abf5a7c88bb8f651408306f53027b1b4f02c7a6bc58a25e6fb7722467b506151952ab55d3879eb046ec385381b731c7809e",
    ephemeralPrivateKey: "0x4a6e6a5a5b8778ede0d88445ad1e0e16dc7fe19be0cfa161841d5b2c291df581",
    ephemeralPublicKey: "0x0357e47ccb8ef2294f5c18f1011cae0a985a446c1d54e0571186af7355a8e16587",
    viewTag: "0x9f",
    stealthAddress: "0x0080Ebc76fD5FA4f2a23968D58516B7ffA2f24F3",
    stealthPrivateKey: "0x2a819f90ece6826882c5e81dff9d9eb94cc4985e7436786035db2c2a7796a838",
  },
  {
    spendingPrivateKey: "0x3be2f605dbd793ebccdf277c26cc71bdda285dac393083dd569fb3545bf347ff",
    viewingPrivateKey: "0x7fe5b252e93d0a551774121101ae968860d7ecc1cb98c59a38fa86f04f86f82b",
    spendingPublicKey: "0x02684cb32eb0181b4e956995899c0278f0844ebdeabde7fada8554989c281b55b2",
    viewingPublicKey: "0x03e95c31cbe17058b50a4581f6266cee3921d800bc8624f98bb4decefa616ce1c4",
    metaAddress: "0x02684cb32eb0181b4e956995899c0278f0844ebdeabde7fada8554989c281b55b203e95c31cbe17058b50a4581f6266cee3921d800bc8624f98bb4decefa616ce1c4",
    ephemeralPrivateKey: "0xdbb177e5ab5c86375e2b222fad359de233b13bfab7812c4f8f41b2c38f1c486b",
    ephemeralPublicKey: "0x032baded9fd87005ac3fe16d01226ff98a9dad66573cc931e98988b10347c9d952",
    viewTag: "0xb6",
    stealthAddress: "0xd969Ba0DeF8562664E81C078332E8Ff349297dce",
    stealthPrivateKey: "0xf2d2de378261c9f9380ef64885d7606bb70694b547373858fc91791c33d46c3c",
  },
  {
    spendingPrivateKey: "0xb9a7bd43c3f74885c1dd3e4fb987c1f7a55535996fe854eb7ef4065d77fa6776",
    viewingPrivateKey: "0x967c0596e105ccdedc51300f3189929e0794caa7aef81115af44e0c0267e8f52",
    spendingPublicKey: "0x026bead5189e04778e3f6613681534b9d86cce5fda9f5b1f8a1f43275f8e62dac3",
    viewingPublicKey: "0x023b52725cf295d6bf81096d1b573950fd91b0d146f9fcab990483f061a06d6ec1",
    metaAddress: "0x026bead5189e04778e3f6613681534b9d86cce5fda9f5b1f8a1f43275f8e62dac3023b52725cf295d6bf81096d1b573950fd91b0d146f9fcab990483f061a06d6ec1",
    ephemeralPrivateKey: "0x8cb512b45835842fc11e132f51d7968d18a49b1fe9c6abf995342149ccefbb78",
    ephemeralPublicKey: "0x03900c2a827b160516cdcfa864649990f6ebacf357e3f69eeeb4e8c9349878699e",
    viewTag: "0x64",
    stealthAddress: "0xd7a1320C20b572D7F817F63C14D8438cfFF20bB1",
    stealthPrivateKey: "0x1daea089cad0cd1d0e2cd744a44c10e3397e4fa5d7c1aa25a1aced7951bbf0f8",
  },
];

/**
 * Signature-to-keys vectors.
 *
 * Unlike the vectors above, this derivation is Ghost Pay's own — ERC-5564 says nothing about where
 * the two keypairs come from, and ScopeLift's SDK splits the signature into halves where we hash it
 * into a seed with domain separators (see `keys.ts`). Nothing on-chain depends on the choice; what
 * depends on it is every existing user's ability to recover their keys. These vectors exist to make
 * an accidental change to that derivation fail loudly instead of silently orphaning funds.
 */
export type KeyVector = {
  signature: Hex;
  spendingPrivateKey: Hex;
  spendingPublicKey: Hex;
  viewingPrivateKey: Hex;
  viewingPublicKey: Hex;
};

export const KEY_VECTORS: KeyVector[] = [
  {
    signature: "0xc589f705bf29508a2853c341704db24e647766b32b8e18b577077dcabc201544b38372b9edf136f4a52bc7a537b333e0fef066416b81c5bdabd3e546f0e95aec1b",
    spendingPrivateKey: "0x4552a75459bd617e545fc0b1984ff450f8b740389f4a25e15c82c216c7510601",
    spendingPublicKey: "0x03cd1ed40fd0e95c587857901850a090878b3db381ff30e86885b800f0d0d3e411",
    viewingPrivateKey: "0x927742c06ea79f9293e20c0acd2e68cf45dae2817af70fa84a36832f69403858",
    viewingPublicKey: "0x026193489665ccf608a359e9b48425fe8c5d47a0e5eb7fd4f8fd5c00aa77245b93",
  },
  {
    signature: "0xb38372b9edf136f4a52bc7a537b333e0fef066416b81c5bdabd3e546f0e95aecb159849c171ab79324b7521eef2a92e878d2cebe45b46ca5d4ab1e9a5f99dcc51c",
    spendingPrivateKey: "0x5ad8c7305b134ed7ae8f574249a10e92691d3af3f5fda0c527c68a82ab1ef54a",
    spendingPublicKey: "0x03a8aec34c50a0c0ee688edc1b89d7b93f481c9ef03a242219235282a257d3ee2b",
    viewingPrivateKey: "0x9347185687d44ef82e9d6897da355b097f2ec68065105b9279e61216ae92ff1a",
    viewingPublicKey: "0x03c1abdcf6ba837ed6275e5d24b90b68757a98574f3883b8f6ab89be389cd58c4d",
  },
  {
    signature: "0xb159849c171ab79324b7521eef2a92e878d2cebe45b46ca5d4ab1e9a5f99dcc578ab4a2980c8ae0ecb94d3602df238b0dafe0898fdc2c9a9a8eddf13145068a41b",
    spendingPrivateKey: "0x975851b14e0ad85f71533b906709bc8921d7945124b8f1d7cf4ce8be1fedd817",
    spendingPublicKey: "0x0304da4fd954932cd1a776906c8ece75217c6acb1976e7399f3d9c7194124c11fe",
    viewingPrivateKey: "0x0e0c4d4c6eeca7043db2749366a25dfe75a764402cacb567b51b9b8482a14e51",
    viewingPublicKey: "0x020b9a5ba6aa515ed3677ec230d494bdd645112f779279c6db8c6cda8880a2653b",
  },
];
